version: "3.9"
services:
  beef:
    image: beef
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./config.yaml:/beef/config.yaml
    ports:
      - "3000:3000"
      - "6789:6789"
      - "61985:61985"
      - "61986:61986"
