version: '3'

services:
  beef:
    build:
      context: .
    volumes:
      - ./config.yaml:/beef/config.yaml
    ports:
    - '3000:3000'
    - '61985:61985'
    - '61986:61986'
    - '6789:6789'
