server: "hub-cloud.browserstack.com"

common_caps:
  "build": "Windows 11 Chrome 103"
  "project": "BeEF"
  "browserstack.local": true
  "browserstack.video": false

browser_caps:
  -
    "browser": "chrome"
    "browser_version": "103.0"
    "os": "windows"
    "os_version": "11”